apiVersion: apps/v1
kind: Deployment
metadata:
 name: mqtt-client-deployment-temperature
spec:
 selector:
  matchLabels:
   app: mqtt-client-temperature
 replicas: 2
 template:
  metadata:
   labels:
    app: mqtt-client-temperature
  spec:
   containers:
   - name: mqtt-client-temperature
     image: aksakalli/mqtt-client
     command: ["bin/sh"]
     args: ['-c', 'id=$(shuf -i 1000-9999 -n 1);topic="temp";while true;do timestamp=$(date "+%Y/%m/%d %H:%M:%S");temperature=$(shuf -i 0-100 -n 1);message="$timestamp Device:$id Temperature:$temperature°C";pub -h 172.24.4.105 -t "$topic" -m "$message" -q 2;sleep 10;done']
     tty: true
