---
- hosts: localhost
  gather_facts: False
  vars:
    private_network_name: private
    private_subnet_name: "{{ private_network_name }}-subnet"
    router_name: "router1"
    instance_name: "nvm1"
  tasks:
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin
  - name: Delete instance "{{ instance_name }}"
    os_server:
      cloud: project_admin
      state: absent
      name: "{{ instance_name }}"
      delete_fip: True
  - name: Delete router "{{ router_name }}"
    os_router:
      cloud: project_admin
      state: absent
      name: "{{ router_name }}"
  - name: Delete subnet "{{ private_subnet_name }}"
    os_subnet:
      cloud: project_admin
      state: absent
      name: "{{ private_subnet_name }}"
  - name: Delete network "{{ private_network_name }}"
    os_network:
      cloud: project_admin
      state: absent
      name: "{{ private_network_name }}"
