---
- hosts: localhost
  gather_facts: False
  vars:
    private_network_name: private
    private_subnet_name: "{{ private_network_name }}-subnet"
    router_name: "router1"
    webserver_name: "web-server"
    mqttbroker_name: "mqtt-broker"
  tasks:
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin

  # instances
  - name: Delete instance "{{ webserver_name }}"
    os_server:
      cloud: project_admin
      state: absent
      name: "{{ webserver_name }}"
  - name: Delete instance "{{ mqttbroker_name }}"
    os_server:
      cloud: project_admin
      state: absent
      name: "{{ mqttbroker_name }}"

  # security groups
  - name: Delete security group "ping-in"
    os_security_group:
      cloud: project_admin
      state: absent
      name: ping-in
  - name: Delete security group "ssh-in"
    os_security_group:
      cloud: project_admin
      state: absent
      name: ssh-in
  - name: Delete security group "web-in"
    os_security_group:
      cloud: project_admin
      state: absent
      name: web-in
  - name: Delete security group "mqtt-in"
    os_security_group:
      cloud: project_admin
      state: absent
      name: mqtt-in

  # key pair
  - name: Delete key pair "eval"
    os_keypair:
      cloud: project_admin
      state: absent
      name: eval

  # router
  - name: Delete router "{{ router_name }}"
    os_router:
      cloud: project_admin
      state: absent
      name: "{{ router_name }}"

  # network
  - name: Delete subnet "{{ private_subnet_name }}"
    os_subnet:
      cloud: project_admin
      state: absent
      name: "{{ private_subnet_name }}"
  - name: Delete network "{{ private_network_name }}"
    os_network:
      cloud: project_admin
      state: absent
      name: "{{ private_network_name }}"
