---
- hosts: localhost
  gather_facts: False
  vars:
    private_network_name: private
    private_subnet_name: "{{ private_network_name }}-subnet"
    router_name: "router1"
    security_groups: [ping-in,ssh-in,web-in,mqtt-in]
    webserver_name: "web-server"
    mqttbroker1_name: "mqtt-broker-1"
    mqttbroker2_name: "mqtt-broker-2"
    loadbalancer_name: "load-balancer"
    database_name: "database"
    instances: ["{{ webserver_name }}","{{ mqttbroker1_name }}","{{ mqttbroker2_name }}","{{ loadbalancer_name }}","{{ database_name }}"]
  tasks:
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin

  # ports
  - name: Delete ports
    os_port:
      cloud: project_admin
      state: absent
      name: "{{ item }}-port"
    loop: "{{ instances }}"

  # security groups
  - name: Delete security groups
    os_security_group:
      cloud: project_admin
      state: absent
      name: "{{ item }}"
    loop: "{{ security_groups }}"

  # router
  - name: Delete router "{{ router_name }}"
    os_router:
      cloud: project_admin
      state: absent
      name: "{{ router_name }}"

  # network
  - name: Delete subnet "{{ private_subnet_name }}"
    os_subnet:
      cloud: project_admin
      state: absent
      name: "{{ private_subnet_name }}"
  - name: Delete network "{{ private_network_name }}"
    os_network:
      cloud: project_admin
      state: absent
      name: "{{ private_network_name }}"

  # key pair
  - name: Delete key pair "eval"
    os_keypair:
      cloud: project_admin
      state: absent
      name: eval
