---
- hosts: localhost
  gather_facts: False
  vars:
    project_name: test
    member_names: [fabio,jaff]
    member_password: password
    reader_name: eval
    reader_password: eval
  tasks:
  - name: Create project '{{ project_name }}'
    os_project:
      state: present
      name: {{ project_name }}
      domain: default
      enabled: True
  - name: Create project member '{{ item }}'
    os_user:
      state: present
      name: {{ item }}
      password: {{ member_password }}
      domain: default
    loop: {{ member_names }}
  - name: Grant member role on the user '{{ item }}' in the project '{{ project_name }}'
    os_user_role:
      user: {{ item }}
      role: member
      project: {{ project_name }}
    loop: {{ member_names }}
