---
- hosts: localhost
  gather_facts: False
  vars:
    webserver_name: "web-server"
    mqttbroker1_name: "mqtt-broker-1"
    mqttbroker2_name: "mqtt-broker-2"
    loadbalancer_name: "load-balancer"
    database_name: "database"
    instances: ["{{ webserver_name }}","{{ mqttbroker1_name }}","{{ mqttbroker2_name }}","{{ loadbalancer_name }}","{{ database_name }}"]
  tasks:
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin
  - name: Delete instances
    os_server:
      cloud: project_admin
      state: absent
      name: "{{ item }}"
    loop: "{{ instances }}"
