---
- hosts: localhost
  gather_facts: False
  vars:
    webserver_name: "web-server"
    mqttbroker_name: "mqtt-broker"
    instances: ["{{ webserver_name }}","{{ mqttbroker_name }}"]
  tasks:
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin
  - name: Delete instances
    os_server:
      cloud: project_admin
      state: absent
      name: "{{ item }}"
    loop: "{{ instances }}"
