---
- hosts: localhost
  gather_facts: False
  vars:
    auth:
      auth_url: http://10.235.1.102/identity
      username: admin
      password: password
      os_user_domain_name: Default
    project_name: test
    member_names: [test_admin,fabio,jaff]
    member_password: password
    reader_name: eval
    reader_password: eval
  tasks:
  - name: Create project "{{ project_name }}"
    os_project:
      state: present
      name: "{{ project_name }}"
      domain: default
      enabled: True
  - name: Create project members
    os_user:
      state: present
      name: "{{ item }}"
      password: "{{ member_password }}"
      domain: default
    loop: "{{ member_names }}"
  - name: Grant member role on the project members
    os_user_role:
      user: "{{ item }}"
      role: member
      project: "{{ project_name }}"
    loop: "{{ member_names }}"
  - name: Create project reader
    os_user:
      state: present
      name: "{{ reader_name }}"
      password: "{{ reader_password }}"
      domain: default
  - name: Grant reader role on the reader member
    os_user_role:
      user: "{{ reader_name }}"
      role: reader
      project: "{{ project_name }}"
