---
- hosts: localhost
  gather_facts: False
  vars:
    project_name: project
    project_admin_name: "{{ project_name }}_admin"
    project_reader_name: eval
    project_users: ["{{ project_admin_name }}","{{ project_reader_name }}"]
    images: [ubuntu-18.04-minimal,ubuntu-18.04-server]
  tasks:
  - name: Authenticate as admin
    os_auth:
      cloud: admin
  - name: Delete project "{{ project_name }}"
    os_project:
      cloud: admin
      state: absent
      name: "{{ project_name }}"
  - name: Delete users
    os_user:
      cloud: admin
      state: absent
      name: "{{ item }}"
    loop: "{{ project_users }}"
  - name: Delete images
    os_image:
      cloud: admin
      state: absent
      name: "{{ item }}"
    loop: "{{ images }}"
