---
- hosts: localhost
  gather_facts: False
  vars:
    project_name: project
    project_admin_name: "{{ project_name }}_admin"
    project_admin_password: password
    project_reader_name: eval
    project_reader_password: eval
  tasks:
  - name: Authenticate as admin
    os_auth:
      cloud: admin
  - name: Create project "{{ project_name }}"
    os_project:
      cloud: admin
      state: present
      name: "{{ project_name }}"
      domain: default
      enabled: True
  - name: Create user "{{ project_admin_name }}"
    os_user:
      cloud: admin
      state: present
      name: "{{ project_admin_name }}"
      password: "{{ project_admin_password }}"
      domain: default
  - name: Grant member role on the user "{{ project_admin_name }}" in the project "{{ project_name }}"
    os_user_role:
      cloud: admin
      user: "{{ project_admin_name }}"
      role: member
      project: "{{ project_name }}"
  - name: Create user "{{ project_reader_name }}"
    os_user:
      cloud: admin
      state: present
      name: "{{ project_reader_name }}"
      password: "{{ project_reader_password }}"
      domain: default
  - name: Grant reader role on the user "{{ project_reader_name }}" in the project "{{ project_name }}"
    os_user_role:
      cloud: admin
      user: "{{ project_reader_name }}"
      role: reader
      project: "{{ project_name }}"
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin
  - name: Upload image "ubuntu-18.04-minimal-cloudimg-amd64.img"
    os_image:
      cloud: project_admin
      name: ubuntu-18.04-minimal
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /var/tmp/ubuntu-18.04-minimal-cloudimg-amd64.img
      checksum: d1cf2f8529f759f05ce55d8d3407de7c3dc7059f94aa521266325cc4d069b834
