---
- hosts: localhost
  gather_facts: False
  vars:
    public_network_name: public
    private_network_name: private
    private_subnet_name: "{{ private_network_name }}-subnet"
    router_name: "router1"
  tasks:
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin
  - name: Create private network "{{ private_network_name }}"
    os_network:
      cloud: project_admin
      state: present
      name: "{{ private_network_name }}"
  - name: Create subnet "{{ private_subnet_name }}" on network "{{ private_network_name }}"
    os_subnet:
      cloud: project_admin
      state: present
      network_name: "{{ private_network_name }}"
      name: "{{ private_subnet_name }}"
      cidr: 10.0.0.0/24
      dns_nameservers:
       - 1.1.1.1
       - 1.0.0.1
  - name: Create router "{{ router_name }}" attached to external network "{{ public_network_name }}" and internal subnet "{{ private_network_name }}-subnet"
    os_router:
    cloud: project_admin
    state: present
    name: "{{ router_name }}"
    network: "{{ public_network_name }}"
    interfaces:
      - "{{ private_network_name }}-subnet"
