---
- hosts: localhost
  gather_facts: False
  vars:
    project_name: project
    project_admin_name: "{{ project_name }}_admin"
    project_admin_password: password
    project_reader_name: eval
    project_reader_password: eval
  tasks:
  - name: Authenticate as admin
    os_auth:
      cloud: admin
  - name: Create project "{{ project_name }}"
    os_project:
      cloud: admin
      state: present
      name: "{{ project_name }}"
      domain: default
      enabled: True
  - name: Create user "{{ project_admin_name }}"
    os_user:
      cloud: admin
      state: present
      name: "{{ project_admin_name }}"
      password: "{{ project_admin_password }}"
      domain: default
  - name: Grant member role on the user "{{ project_admin_name }}" in the project "{{ project_name }}"
    os_user_role:
      cloud: admin
      user: "{{ project_admin_name }}"
      role: member
      project: "{{ project_name }}"
  - name: Create user "{{ project_reader_name }}"
    os_user:
      cloud: admin
      state: present
      name: "{{ project_reader_name }}"
      password: "{{ project_reader_password }}"
      domain: default
  - name: Grant reader role on the user "{{ project_reader_name }}" in the project "{{ project_name }}"
    os_user_role:
      cloud: admin
      user: "{{ project_reader_name }}"
      role: reader
      project: "{{ project_name }}"
  - name: Upload image "ubuntu-18.04-minimal"
    os_image:
      cloud: admin
      state: present
      name: ubuntu-18.04-minimal
      container_format: bare
      disk_format: qcow2
      filename: /var/tmp/ubuntu-18.04-minimal-cloudimg-amd64.img
      min_disk: 2
      min_ram: 384
  - name: Upload image "ubuntu-18.04-server"
    os_image:
      cloud: admin
      state: present
      name: ubuntu-18.04-server
      container_format: bare
      disk_format: qcow2
      filename: /var/tmp/ubuntu-18.04-server-cloudimg-amd64.img
      min_disk: 2
      min_ram: 512
  - name: Authenticate as project admin
    os_auth:
      cloud: project_admin
